baseurl = "/"
publishDir = "docs"
relativeurls = true
languageCode = "en-us"
title = "Live Free or Dichotomize"
theme = "hugo-theme-casper"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/lfod/blog"
[[menu.main]]
    name = "Lucy's Twitter"
    url = "https://twitter.com/LucyStats"
[[menu.main]]
    name = "Nick's Twitter"
    url = "https://twitter.com/NickStrayer"

[params]
    description = "A statistics blog from two goofy Phd students."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    logo = "images/logo.png"
    cover = "images/spline_regression.png"
