baseurl = "/"
publishDir = "docs"
relativeurls = true
languageCode = "en-us"
title = "Live Free or Dichotomize"
theme = "tuftesque"
disqusShortname = "livefreeordichotomize"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
author = "Nick Strayer & Lucy D'Agostino McGowan"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
[[menu.main]]
    name = "Lucy's Twitter"
    url = "https://twitter.com/LucyStats"
[[menu.main]]
    name = "Nicks's Twitter"
    url = "https://twitter.com/NicholasStrayer"    

[params]
    description = "A statistics blog from two goofy Phd students."
    googleAnalytics = "UA-92165973-1"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    
    showtitle = false
    [params.logo]
    url = "/images/logo.png"
    width = 50
    height = 50
    alt = "Logo"
