---
author: "Lucy D'Agostino McGowan"
comments: true
date: 2017-01-17T22:15:13-06:00
draft: false
image: ""
menu: ""
share: true
tags: ["rms"]
excerpt: "Nick and I are starting a series following Frank Harrell's Regression Modeling Strategies course. Get ready for some crazy fun."
title: "Regression modeling strategies: a student's perspective"
---

Frank Harrell teaches an amazing course "Regression Modeling Strategies" based on his [book](https://www.amazon.com/Regression-Modeling-Strategies-Applications-Statistics/dp/3319194240/ref=sr_1_1?ie=UTF8&qid=1484713166&sr=8-1&keywords=regression+modeling+strategies) each spring at Vanderbilt. 

This was one of my all time favorite courses. It has just the right amount of practical strategies, brilliant statistical insight, and zealous disdain for all things stepwise regression. In fact, Frank's valiant fight against dichotomization inspired the name of this very blog.

This semester, Nick is enrolled in the course, and I will be TAing it, so we thought it would be a perfect time to do what all good 21st century students do, blog about it. We will be using the #rms tag to thread the series to make it easy to follow along.

To kick things off, I encourage everyone to get a flavor of our beloved professor's style by trying out the following `R` code:


```
library("fortunes")
fortune("Harrell")
```

Here is one of my personal favorites:


```{r, echo = FALSE}
set.seed(6)
library(fortunes)
fortune("Harrell")
```

We have been planning on kicking this series off for a while, but it happens to serendipitously coincide with Frank jumping online via [twitter](www.twitter.com/f2harrell) and a [blog](http://www.fharrell.com)! We are so excited to see how this goes.  
