---
title: 'First year as faculty'
author: "Lucy D'Agostino McGowan"
date: '2020-05-15'
slug: first-year-as-faculty
categories: []
tags: []
math: no
meta: yes
excerpt: "I just completed my first year as a faculty member - here is what I've learned! I'll start by giving some context for where I am, what my university is like, etc. Then I'll describe four recommendations, summarized by: discover your institution's culture, become a peer, find harmony, and build community!"
---

I just completed my first year as a faculty member - here is what I've learned! I'll start by giving some _context_ for where I am, what my university is like, etc. Then I'll describe four recommendations, summarized by:

`r emo::ji("performing_arts")` Discover your institution's culture      
`r emo::ji("woman_office_worker")` Become a peer   
`r emo::ji("notes")` Find harmony   
`r emo::ji("dancing_women")` Build community 

Here we gooo!

## Context

_Where am I? How does this compare to where you are going?_

* I'm an assistant professor at Wake Forest University  `r tufte::margin_note("R1? R2? What are these acronyms? The [Carnegie Classification of Institutions of Higher Education](http://carnegieclassifications.iu.edu) is a way to classify institutions, briefly, R1: Doctoral Universities – Very high research activity, R2: Doctoral Universities – High research activity.")`
* Wake is an R2, I think of it as a "hybrid" between a teaching-focused institution (like an SLAC) & a research-focused one (like an R1) (this is not to say that folks at SLACs don't do research or people at R1s don't focus on teaching!)    
* The official breakdown of my responsibilities are: 

`r emo::ji("woman_teacher")` **45%** teaching  
`r emo::ji("woman_scientist")` **45%** research  
`r emo::ji("woman_mechanic")`  **10%** service

* On the **teaching** side, we have a 2-2 teaching load, small (< 35 students) classes, and are very undergraduate focused  
* On the **research** side, grant funding is encouraged, I was given lab space and start-up funds to build a lab, my lab will be predominantly filled with undergraduate students

## Culture

_Getting to know your new academic home_

In my first year I've tried to navigate the norms. There are several layers to explore here, for example there are university norms, departmental norms, and within your department, there may be norms within your specialty. Here are some things I thought about:

### University norms

* **Meetings**: Figure out which meetings assistant professors usually attend. There are a lot of meetings that are open to all faculty. Figuring out where to spend your _limited_ time is crucial!  
* **Service roles**: Figure out what types of service roles are typically expected of incoming faculty  
* **Visibility**: Figure out where it is important to be _visible_. Outside of meetings and service roles, there are often several other events (such as professional development opportunities, socials, etc). Ask around to figure out which will give the most bang for your buck in terms of helping your long term career goals

### Departmental norms

* **Meetings**: Figure out how meetings are run. For example, does your department like to follow [Robert's Rules of Order](https://en.wikipedia.org/wiki/Robert's_Rules_of_Order) for all meetings? Are there unspoken expectations about where people should sit? A tradition in my department is for everyone to sit in equally visible seats, some of these traditions are not necessarily reiterated at the beginning of each year, so it can be helpful to ask!
* **Being heard**: Figure out the best way to have your voice heard. Are you particularly passionate about curriculum choices for the Introduction to Statistics course? Figure out how those decisions are made at the department-level. Maybe it means you should request to join a committee, or maybe it means you should set up some coffee chats with the faculty member that tends to make these decisions   
* **Visibility**: Figure out where/when it is important to be _visible_. Different departments have different cultures with respect to whether professors tend to work with their doors open, do people tend to work from home when they aren't teaching, etc. Ask around to see if such expectations exist in your new academic home!  
* **Being a team player**: Being on faculty is so exciting, you are joining a new team of people who all have (academic) interests like you! Figuring out how to best contribute to the team is an exciting and important prospect in the first year!  

## Becoming a peer

_The transition from graduate student / postdoc to peer_

As with any job after being a student for quite some time, it can be difficult to figure out how to transition from being a student to being a peer! For me, this manifested in three ways:

* **Collaboration:** Figure out what your role is as a collaborator. Transitioning from being a collaborator on projects as a student to being a collaborator as a peer can be challenging!  
* **Your name**: Take some time to consider what you would like to be called, both in the classroom and in collaborations. For example, would you like to go by Dr. ---, or Professor? or by your first name? There is not just one right answer here, but it's worth taking into consideration in your first year. It is also worth considering that your decision (like lots of decisions we make!) may have ripple effects outside of just you. For example, if you go by your first name, it may make it difficult for your colleagues to make a different decision.   
* **Graduate students**: Consider if/how you will work with graduate students. This was difficult for me to navigate! Even with a postdoc between graduate school and my faculty position, I felt like I _was_ a graduate five seconds ago, how can I be leading graduate student research now? For me, I oscillate between a bit of humility along with a bit of confidence.   

## Finding harmony

_Between teaching, research, and service_

I like the word _harmony_ here instead of _balance_. I think of this similarly to how I think about work-life "balance". We're really striving for _harmony_ and long-run averages rather than day-to-day balance!

<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">I like work-life harmony! I don’t think balance ⚖️ is really always the goal (like, with a small baby it’s going to tip towards life, with a grant deadline it’ll top towards work, but keeping things in harmony is the goal) <a href="https://t.co/oJO8ZyHo8T">pic.twitter.com/oJO8ZyHo8T</a></p>&mdash; Lucy D’Agostino McGowan (@LucyStats) <a href="https://twitter.com/LucyStats/status/1242803985242882049?ref_src=twsrc%5Etfw">March 25, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

### Teaching

Teaching, especially in your first year if you're building new courses, can take up lots of time, and for the most part I think this is great! A lot of that investment will pay dividends in the future! It can be good to consistently take a look at how you're spending your time throughout the year to make sure you're striking a nice harmony `r emo::ji("smile")`. I found that it was possible to spend infinite time tweaking my teaching, whether it was finding the perfect dataset to use as an example or developing thought-provoking yet complex-enough exam questions. Some of this time was definitely well spent and some of it maybe less so. Finding a strategy to be able to assess what is time well spent and what isn't can be really useful! Given the lack of infinite time, some strategies I found helpful include:

* Teaching in blocks. I request to teach on Tuesday and Thursday back-to-back. This helps me focus on my teaching on these days; this strategy works well for me, but I know many others that like other schedules! Find one that works best with your flow!   
* Contentiously schedule non-teaching time on your calendar. I found it really useful to block off time on my calendar specifically to be spent on _other_ tasks  

### Research

If you plan on doing research, here are a few things I would recommend in year one!

* Get to know the administration - they will be your friends and advocates in getting your research agenda off the ground!  
* Familiarize yourself with procedures, i.e. how are reimbursements processed, how early do you need grant submissions internally routed before they can be officially submitted, who do you need to talk to about paying graduate students  
* If you plan on getting grant funding, apply ASAP if for nothing else to figure out the _process_. This is not a totally popular opinion, but I found it really helpful. I was on several grants as a graduate student and postdoc, however I never organized one from start to finish myself. The process was really eye opening - I think getting this experience early can be really useful, especially if you will rely on the funding.

### Service

Service is tricky because I _LOVE_ service roles and yet, again, I don't have infinite time. I have been given the advice several times that it’s unusual for strong service to make up for not-so-strong teaching / research, so this balance is very important. That being said, if you are interested in serving in particular leadership roles, I've found it very helpful to make that desire known, especially to senior colleagues. Many folks in senior positions are given leadership opportunities that they are more than happy to pass down.

## Community

_Finding a community of mentors / peers to uplift you_

### Mentors

It can be so helpful in this first year to find mentors to help you shape and achieve your short and long term career goals. I have found it the _most_ useful to have at least one mentor: inside the department, outside the department but inside the university, outside the university. These mentors have helped me navigate all of the previous sections mentioned here!

### Peers

In addition to mentors, having peers to bounce ideas off of, complain to, and uplift, is super helpful! Peers both inside your department and outside are crucial! For example, I spend a lot of time on the [New PI Slack](https://newpislack.wordpress.com) - a community for assistant professors around the world.

## Wrap up

SO there it is. Some things I've learned in my first year. In sum, four things to focus on:

`r emo::ji("performing_arts")` Discover your institution's culture      
`r emo::ji("woman_office_worker")` Become a peer   
`r emo::ji("notes")` Find harmony   
`r emo::ji("dancing_women")` Build community 

I look forward to learning lots more in the years to come!

